# -*- coding: utf-8 -*-
"""BankNote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1huE87jje-uK44Sc3lRfBuVcdHHHU9ZDg
"""

#Import Liabraries
import pandas
import numpy
from sklearn.ensemble import RandomForestClassifier 
import pickle

#preprocessing of dataframe using the data at given link and defined columns list
dataframe = pandas.read_csv("/content/BankNote_Authentication.csv")

array = dataframe.values
array

# separate array into input and output components
X = array[:,:-1]
y = array[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

score

pickle_out = open("BankNote.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

classifier.predict([[2,3,4,1]])

